version: '3.8'
services:
  head:
    build: .
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 4000 --reload
    ports:
      - "4000:4000"
    env_file:
      - .env.example
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: proxeratech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:7
